=== Khmelov/JD2017-02-20/src/by/it/ikavalenka/jd02_07/InShop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://ikavalenka.it-academy.by/xml/InternetShop"
        xmlns:tns="http://ikavalenka.it-academy.by/xml/InternetShop"
        elementFormDefault="qualified">

    <element name="InternetShop">
    <complexType>
    <sequence>
    <element name="Administrator" type="tns:Administrator"/>
    <element name="Client" type="tns:Client"/>
    <element name="OrderC" type="tns:OrderC"/>
    <element name="BlackListStatus" type="tns:BlackListStatus"/>
    </sequence>
    </complexType>
    </element>

    <element name="Administrator">
            <complexType>
                <sequence>
                    <element name="Administrator"
                            type="tns:Administrator"
                            minOccurs="2"
                            maxOccurs="unbounded">
                    </element>
                </sequence>
            </complexType>
    </element>

    <complexType name="Administrator">
            <sequence>
    <element name="Catalog" type="string"/>
    <element name="Order" type="integer"/>
    <element name="BlackList" type="string"/>
            </sequence>
        <attribute name="login" type="tns:Login" use="required" />
        <attribute name="password" type="tns:Password" use="required" />
    </complexType>


    <complexType name="Clients">
            <sequence>
                    <element name= "Client" type="tns:Client"
                             minOccurs="2"
                             maxOccurs="unbounded"/>
    </sequence>
    </complexType>
    <complexType name="Client">
        <sequence>
    <element name="MadeOrder" type="string"/>
    <element name="PayOreder" type="double"/>
            </sequence>
        <attribute name="login" type="tns:Login" use="required" />
        <attribute name="password" type="tns:Password" use="required" />
    </complexType>
    <complexType name="OrderC">
        <sequence>
                <element name="Profit" type="string"/>
                <element name="Count" type="string"/>
                <element name="Sale" type="string"/>
        </sequence>
    </complexType>
    <complexType name="BlackListStatus">
        <sequence>
            <element name="Client_id" type="integer"/>
        </sequence>
    </complexType>
    <simpleType name ="Login">
        <restriction base="string">
                <pattern value="([a-zA-Z])[a-zA-Z0-9]{1,19}"/>
                        </restriction>
    </simpleType>

    <simpleType name="Password">
        <restriction base="string">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{1,19}"/>
        </restriction>
    </simpleType>
</schema>

=== Khmelov/JD2017-02-20/src/by/it/ikavalenka/jd02_07/InternetShop.xml
<?xml version="1.0" encoding="UTF-8"?>
<InternetShop xmlns="http://by/it/ikavalenka/jd02_07/xml/InternetShop"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://by/it/ikavalenka/jd02_07/xml/InternetShop InShop.xsd">

    <Administrator login="zAds36" password='pass2'>
        <Catalog>CatalogAll</Catalog>
        <Order>12</Order>
        <BlackList>None</BlackList>
    </Administrator>

    <Client login="xAbz46" password='pass1'>
        <MadeOrder>OrderOne</MadeOrder>
        <PayOreder>1343.15</PayOreder>
    </Client>

    <OrderC>
        <Profit>Summary</Profit>
        <Count>AllDevice</Count>
        <Sale>Procent</Sale>
    </OrderC>

    <BlackListStatus>
        <Client_id>458</Client_id>
    </BlackListStatus>
</InternetShop>
