=== Khmelov/JD2017-02-20/src/by/it/ikavalenka/jd02_07/schemaIS.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT InternetShop (Administrator,Client,OrderC,BlackListStatus)+>

        <!ELEMENT Administrator (Catalog,Order,BlackList)+>
        <!ATTLIST Administrator login ID #REQUIRED password ID #REQUIRED>
        <!ELEMENT Catalog (#PCDATA)>
        <!ELEMENT Order (#PCDATA)>
        <!ELEMENT BlackList (#PCDATA)>

        <!ELEMENT Client (MadeOrder,PayOreder) >
        <!ATTLIST Client login ID #REQUIRED password ID #REQUIRED>
        <!ELEMENT MadeOrder (#PCDATA)>
        <!ELEMENT PayOreder (#PCDATA)>

        <!ELEMENT OrderC (Profit,Count,Sale)>
        <!ELEMENT Profit (#PCDATA)>
        <!ELEMENT Count (#PCDATA)>
        <!ELEMENT Sale (#PCDATA)>

        <!ELEMENT BlackListStatus (Client_id)>
        <!ELEMENT Client_id (#PCDATA)+>

=== Khmelov/JD2017-02-20/src/by/it/ikavalenka/jd02_07/schemaIS+DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InternetShop SYSTEM "schemaIS.dtd">

<InternetShop>

<Administrator login="zAds36" password='pass2'>
    <Catalog>CatalogAll</Catalog>
    <Order>OrderNumber</Order>
    <BlackList>None</BlackList>
</Administrator>

<Client login="login_1" password='pass_1'>
<MadeOrder>OrderOne</MadeOrder>
<PayOreder>1343.15</PayOreder>
</Client>

<OrderC>
<Profit>Summary</Profit>
<Count>CountFull</Count>
<Sale>Procent</Sale>
</OrderC>

 <BlackListStatus>
<Client_id>458</Client_id>
 </BlackListStatus>

</InternetShop>
